package com.didekinservice.incidservice.gcm;


import static com.didekin.incidservice.gcm.GcmClientConstant.incidencia_type;

/**
 * User: pedro@didekin
 * Date: 04/12/15
 * Time: 13:10
 * <p>
 * Abstract class that defines objects for HTTP JSON messages with 'data' as payload.
 */
@SuppressWarnings({"unused", "FieldCanBeLocal", "WeakerAccess"})
public abstract class GcmIncidRequest {

    // OPTIONS in request messages.
    private static final String PRIORITY_NORMAL = "normal";
    private static final int TIME_TO_LIVE_DEFAULT = 1724; //48h.
    private static final boolean DELAY_WHILE_IDLE = false;
    private static final String PACKAGE_DIDEKINDROID = "com.didekindroid";

    /**
     *  This parameter specifies the custom key-value pairs of the message's payload.
     */
    private final GcmIncidRequestData data;

    /**
     *  This parameter identifies a group of messages that can be collapsed, so that only the last message
     *  gets sent when delivery can be resumed.
     *  A maximum of 4 different collapse keys is allowed at any given time.
     */
    private final String collapse_key;

    /**
     *  Sets the priority of the message. Valid values are "normal" and "high."
     */
    private final String priority;

    /**
     *  When this parameter is set to true, it indicates that the message should not be sent until the device becomes active.
     *  The default value is false.
     */
    private final boolean delay_while_idle;

    /**
     *  This parameter specifies how long (in seconds) the message should be kept in FCM storage if the device is offline.
     *  The maximum time to live supported is 4 weeks, and the default value is 4 weeks.
     *  The default value is false.
     */
    private final int time_to_live;


    /**
     *  This parameter specifies the package name of the application where the registration tokens must match in order to receive the message.
     */
    private final String restricted_package_name;

    {
        collapse_key = incidencia_type;
        priority = PRIORITY_NORMAL;
        delay_while_idle = DELAY_WHILE_IDLE;
        time_to_live = TIME_TO_LIVE_DEFAULT;
        restricted_package_name = PACKAGE_DIDEKINDROID;
    }

    private GcmIncidRequest(long comunidadId)
    {
        data = new GcmIncidRequestData(comunidadId);
    }

    public GcmIncidRequestData getData()
    {
        return data;
    }

    //    ======================= INNER CLASSES for implementations ==========================

    /**
     * GcmIncidRequestAbstract implementation for multi-recipients messages.
     */
    public static final class Multicast extends GcmIncidRequest {

        /**
         *  This parameter specifies a list of devices (registration tokens, or IDs) receiving a multicast message.
         *  It must contain at least 1 and at most 1000 registration tokens.
         *  Multicast messages (sending to more than 1 registration tokens) are allowed using HTTP JSON format only.
         *
         *  A registration token is an ID generated by the FCM SDK for each client app instance.
         */
        private final String[] registration_ids;

        public Multicast(long comunidadId, String[] registration_ids)
        {
            super(comunidadId);
            this.registration_ids = registration_ids.clone();
        }

        String[] getRegistrationIds()
        {
            return registration_ids.clone();
        }
    }

    /**
     * GcmIncidRequest implementation for single recipient messages.
     */
    public static final class Single extends GcmIncidRequest {

        /**
         *  This parameter specifies the recipient of a message.
         *  The value must be a registration token, notification key, or topic.
         */
        private final String to;

        public Single(long comunidadId, String to)
        {
            super(comunidadId);
            this.to = to;
        }

        public String getTo()
        {
            return to;
        }
    }

//    ======================= INNER CLASSES for data  ==========================

    /**
     * This class is used for 'data' JSON payload in FCM incidencia messages.
     */
    public static class GcmIncidRequestData {

        final String typeMsg;
        final long comunidadId;

        public GcmIncidRequestData(long comunidadId)
        {
            this.comunidadId = comunidadId;
            typeMsg = incidencia_type;
        }
    }
}